export default async function handler(req, res) {
  // Vercel Cron chiama con GET, proteggo con secret
  const authHeader = req.headers['authorization']
  if (authHeader !== `Bearer ${process.env.CRON_SECRET}`) {
    return res.status(401).json({ error: 'Non autorizzato' })
  }

  const SUPABASE_URL = 'https://hdgiwrwcxfbojqfeyrxn.supabase.co'
  const SERVICE_KEY = process.env.SUPABASE_SERVICE_KEY
  const headers = {
    'apikey': SERVICE_KEY,
    'Authorization': `Bearer ${SERVICE_KEY}`,
    'Content-Type': 'application/json',
  }

  try {
    // Prendi tutti i clienti
    const clientsRes = await fetch(`${SUPABASE_URL}/rest/v1/profiles?role=eq.client&select=id,full_name`, { headers })
    const clients = await clientsRes.json()

    const results = []
    const today = new Date().toISOString().split('T')[0]
    const thirtyDaysAgo = new Date(Date.now() - 30*24*60*60*1000).toISOString().split('T')[0]

    for (const client of clients) {
      // Controlla se ha già ricevuto un report negli ultimi 28 giorni
      const lastReportRes = await fetch(`${SUPABASE_URL}/rest/v1/monthly_reports?client_id=eq.${client.id}&order=report_date.desc&limit=1`, { headers })
      const lastReports = await lastReportRes.json()
      const lastReport = lastReports[0]

      if (lastReport) {
        const daysSince = (new Date(today) - new Date(lastReport.report_date)) / (1000*60*60*24)
        if (daysSince < 28) {
          results.push({ client: client.full_name, skipped: true, reason: `report recente (${Math.round(daysSince)}gg fa)` })
          continue
        }
      }

      // Genera il report tramite l'API esistente
      try {
        const baseUrl = process.env.VERCEL_URL ? `https://${process.env.VERCEL_URL}` : 'https://fofit.fit'
        const reportRes = await fetch(`${baseUrl}/api/monthly-report`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ clientId: client.id, autoGenerated: true })
        })
        const reportData = await reportRes.json()
        if (reportData.content) {
          results.push({ client: client.full_name, success: true })
        }
      } catch(e) {
        results.push({ client: client.full_name, error: e.message })
      }

      // Pausa tra le chiamate AI per non sovraccaricare
      await new Promise(r => setTimeout(r, 2000))
    }

    return res.status(200).json({ generated: results.filter(r=>r.success).length, total: clients.length, results })
  } catch(e) {
    return res.status(500).json({ error: e.message })
  }
}
