export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*')
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS')
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type')
  if (req.method === 'OPTIONS') return res.status(200).end()
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' })

  const SUPABASE_URL = 'https://hdgiwrwcxfbojqfeyrxn.supabase.co'
  const SERVICE_KEY = process.env.SUPABASE_SERVICE_KEY
  const ANTHROPIC_KEY = process.env.ANTHROPIC_API_KEY

  const headers = {
    'apikey': SERVICE_KEY,
    'Authorization': `Bearer ${SERVICE_KEY}`,
    'Content-Type': 'application/json',
  }

  try {
    const { clientId, autoGenerated } = req.body
    if (!clientId) return res.status(400).json({ error: 'clientId mancante' })

    const periodEnd = new Date().toISOString().split('T')[0]
    const periodStart = new Date(Date.now() - 30*24*60*60*1000).toISOString().split('T')[0]

    // Raccoglie dati del periodo
    const [profRes, progressRes, logsRes, sessionsRes, diaryRes, checkinRes] = await Promise.all([
      fetch(`${SUPABASE_URL}/rest/v1/profiles?id=eq.${clientId}&select=full_name,goal`, { headers }),
      fetch(`${SUPABASE_URL}/rest/v1/progress_entries?client_id=eq.${clientId}&entry_date=gte.${periodStart}&select=*&order=entry_date.asc`, { headers }),
      fetch(`${SUPABASE_URL}/rest/v1/workout_logs?client_id=eq.${clientId}&log_date=gte.${periodStart}&select=*`, { headers }),
      fetch(`${SUPABASE_URL}/rest/v1/workout_sessions?client_id=eq.${clientId}&session_date=gte.${periodStart}&select=*&order=session_date.asc`, { headers }),
      fetch(`${SUPABASE_URL}/rest/v1/diary_entries?client_id=eq.${clientId}&entry_date=gte.${periodStart}&select=entry_date,kcal,protein_g&order=entry_date.asc`, { headers }),
      fetch(`${SUPABASE_URL}/rest/v1/weekly_checkins?client_id=eq.${clientId}&week_date=gte.${periodStart}&select=*&order=week_date.asc`, { headers }),
    ])

    const [profile] = await profRes.json()
    const progress = await progressRes.json()
    const logs = await logsRes.json()
    const sessions = await sessionsRes.json()
    const diary = await diaryRes.json()
    const checkins = await checkinRes.json()

    // Calcola statistiche
    const firstWeight = progress[0]?.weight_kg
    const lastWeight = progress[progress.length-1]?.weight_kg
    const weightDiff = firstWeight && lastWeight ? (lastWeight - firstWeight).toFixed(1) : null
    const totalSessions = sessions.length
    const totalVolume = logs.reduce((s,l) => s + ((l.weight_kg||0)*(l.reps_done||0)), 0)
    const diaryDays = diary.length
    const avgKcal = diaryDays > 0 ? Math.round(diary.reduce((s,d) => s+(d.kcal||0),0)/diaryDays) : null
    const avgEnergy = checkins.length > 0 ? (checkins.reduce((s,c)=>s+(c.energy||0),0)/checkins.length).toFixed(1) : null
    const avgSleep = checkins.length > 0 ? (checkins.reduce((s,c)=>s+(c.sleep||0),0)/checkins.length).toFixed(1) : null
    const avgStress = checkins.length > 0 ? (checkins.reduce((s,c)=>s+(c.stress||0),0)/checkins.length).toFixed(1) : null

    const prompt = `Sei il coach Federico Obinu. Scrivi un report mensile personalizzato per il tuo cliente ${profile?.full_name || 'il cliente'}.

DATI DEGLI ULTIMI 30 GIORNI (${periodStart} → ${periodEnd}):
- Obiettivo: ${profile?.goal || 'non specificato'}
- Peso: ${firstWeight ? `${firstWeight}kg → ${lastWeight}kg (${weightDiff > 0 ? '+' : ''}${weightDiff}kg)` : 'dati non disponibili'}
- Allenamenti completati: ${totalSessions}
- Volume totale sollevato: ${totalVolume > 0 ? `${Math.round(totalVolume/1000*10)/10}t` : 'non disponibile'}
- Giorni diario alimentare compilato: ${diaryDays}/30
- Kcal medie giornaliere: ${avgKcal || 'non disponibile'}
- Check-in settimanali: energia media ${avgEnergy||'n/d'}/5, sonno ${avgSleep||'n/d'}/5, stress ${avgStress||'n/d'}/5

ISTRUZIONI:
- Tono professionale ma caldo, da coach motivante
- Massimo 250 parole
- Struttura: 1) Risultati del mese (dati concreti) 2) Punti di forza 3) Cosa migliorare 4) Obiettivo del prossimo mese
- Usa il nome del cliente
- Sii specifico, non generico
- NON usare emoji o markdown, solo testo semplice`

    const aiRes = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'x-api-key': ANTHROPIC_KEY, 'anthropic-version': '2023-06-01' },
      body: JSON.stringify({ model: 'claude-sonnet-4-6', max_tokens: 600, messages: [{ role: 'user', content: prompt }] })
    })
    const aiData = await aiRes.json()
    const content = aiData.content?.[0]?.text || 'Report non disponibile'

    // Salva il report
    const saveRes = await fetch(`${SUPABASE_URL}/rest/v1/monthly_reports`, {
      method: 'POST',
      headers: { ...headers, 'Prefer': 'return=representation' },
      body: JSON.stringify({ client_id: clientId, report_date: periodEnd, content, period_start: periodStart, period_end: periodEnd, auto_generated: autoGenerated || false })
    })
    const saved = await saveRes.json()

    return res.status(200).json({ report: saved[0], content })
  } catch(e) {
    return res.status(500).json({ error: e.message })
  }
}
